= script_name(1)
:author: Mark J. Jensen
:authorinitials: mjj
:doctype: manpage
:mandate: 2026-04-12
:man_rel_name: Working Draft
:mantitle: script_name(1)
:manversion: 0.0.2
:manvolume: 1
:script_name: script_name

== Name

{script_name} - One line description of what the script does.

// Copy ols_man_script_adoc to your new script file and
// change the name of the script in the title and
// in the :script_name: variable. Update the one line description
// of what the script does.


== Synopsis

*{script_name}*
[*--input*=_input_file_ | *-i* _input_file_]
[*--output*=_output_file_ | *-o* _output_file_]
[*--help*]
[*--log*]
[*--quiet*]
[*--usage*]
[*--debug*]
[*--version*]
[*--verbose*]
[*--*]
[_input_file_ ...]


== Description

Write a detailed describe of the function of *{script_name}*. What does it do?

May include numerous subsections (_i.e._, === head2, ==== head3, _etc._).

Remove sections that do not apply.


== Options & Arguments

// Add and document the particular options for your script here. Do not remove the standard options,
// that is why they are standard.

[*--option*]:: Description of the option. If the option can be used multiple times, mention that as well.

[*--option*=<value>]:: Description of the option with an value. Describe the argument and its possible values. If the option can be used multiple times, mention that as well.

=== Standard Options

[horizontal]

[*--input*=_input_file_ | *-i* _input_file_]:: If no input files are specified, _i.e._, *--input* or *-i*, the input is read from standard in, _STDIN_. Multiple input files are supported. If no input or output files are specified, *{script_name}* copies _STDIN_ to _STDOUT_ much like cat. If no input file or _STDIN_ exists, *{script_name}* exits gracefully with a exit code of 0.

[*--output*=_output_file_ | *-o* _output_file_]:: If no output file is specified, _i.e._, --output or -o, the output is written to _STDOUT_. If no input or output files are specified, *{script_name}* copies _STDIN_ to _STDOUT_ much like cat. Do not use the same file as an input_file and as an output_file, see <<input_output_restriction,warning>>.

[*--help*]:: Print the help message to standard error, _STDERR_, and exit with an exit code of 0.

[*--log*]:: Log significant events to _STDERR_.

[*--quiet*]:: Only print fatal error messages to _STDERR_.

[*--usage*]:: Print the usage message to standard error, _STDERR_, and exit with an exit code of 0.

[*--debug*]:: Turn on the debug switch.

[*--version*]:: Print the version, copyright, and license message to standard error, _STDERR_, and exit with an exit code of 0.

[*--verbose*]:: Turn on the verbose switch.

[*--*]:: File list marker. The the double dash, `--`, on the command line signals the end options. The remaining items arguments,
even if some look like options.

[_input_files_]:: Additional input files.


== Exit Status

Here is a list of the exit codes that *{script_name}* can return, along with an explanation of each code. The exit code is a number between 0 and 255, where 0 indicates successful completion and any non-zero value indicates an error or warning.

[horizontal]

EX = 0:: Successful completion.

EX = 4:: Warning, but the script completed successfully.

EX = 8:: Error, but part of the script completed okay.

EX &ge; 16:: Fatal Error, the script did not complete successfully.


== Errors

A list of every error and warning message that the script can generate
(even the ones that will &ldquo;never happen&rdquo;), with a full explanation
of each problem, one or more likely causes, and any suggested remedies.

The format of each error number is a 8-character code that has the following structure:

[horizontal]

ZZZ:: A three letter code that identifies this script.

9999:: A four digit code that identifies the particular error message.

X:: A single letter code that identifies the severity of the error message.
* &ldquo;I&rdquo; is an informational message
* &ldquo;W&rdquo; is a warning
* &ldquo;E&rdquo; is an error
* &ldquo;F&rdquo; is a fatal error. 23 skidoo.


=== ZZZ9998X

routine: Error message

[horizontal]

Severity:: Fatal Error, Exit Code 16

Explanation:: Why was this error message generated.

System Action:: The system action depends upon the error conditions described in the accompanying messages.

User Response:: See the specific error message to determine the user action.

Programmer Response:: See the specific error message to determine the programmer action.

System Programmer Response:: See the specific error message to determine the system programmer action.

=== ZZZ9999X

routine: Error message

[horizontal]

Severity:: Fatal Error, Exit Code 16

Explanation:: Why was this error message generated.

System Action:: The system action depends upon the error conditions described in the accompanying messages.

User Response:: See the specific error message to determine the user action.

Programmer Response:: See the specific error message to determine the programmer action.

System Programmer Response:: See the specific error message to determine the system programmer action.


== Environment

=== Variables

No environmental variables were hurt during the development of this script.


== Dependencies

A list of all of the other scripts that this script relies upon, including any restrictions on versions, part of this script's distribution, or must be installed separately.


== Files

A list of the files that are used by this script.

=== Input Files

==== _STDIN_

Describe the _STDIN_ input file format and content.

==== Other Input Files

Describe the other input files format and content.

=== Output Files

==== _STDOUT_

Describe the _STDOUT_ output file format and content.

==== _STDERR_

Describe the _STDERR_ output file format and content.

=== Other Output Files

Describe the other output file format and content.


== Version

[cols="1,1,1,1", options="header"]
|===
| Version
| Author
| Description
| Date

| 0.0.1
| Mark J. Jensen
| 2026-03-31
| Initial Release

| {manversion}
| {author}
| {docdate}
| {man_rel_name}

|===


== Security

NOTE: You must be the superuser to run this script.

WARNING: This script contains security info. Do not set world-readable. Better yet, redesign so that security information is not saved in your source code.

NOTE: This script does not need root/superuser/administrator permission to function.

NOTE: This script does not contain any security info.


== Standards

A list of the standards that this script complies with.


== Notes & Caveats

[#input_output_restriction]
WARNING: Input file and Output File Restriction

Do not use the same file as an input and output in the same command of *{script_name}*. You will
destroy your data. *{script_name}* checks for *--input* and *--output* being equal; however,
you should not do this in the first place.

[.line-through]#{script_name} --input=_file-one_ > _file-one_#


== Bugs & Limitations

A list of all known bugs in the script, including any workarounds.


== Examples

Insert instructive examples here.

Multiple input files are valid, _e.g._,

[source,bash]
----
 {script_name} -i file1 --input=file2 file3 file4 file5
----

A single output file is valid, _e.g._,

[source,bash]
----
 {script_name} -i file1 -o output.file
----

== Frequently Asked Questions

Correct answers to common questions about the script. Remove this section if there are no FAQs.

== Acknowledgements

Whoever you want to thank for their help in the development of this script. Remove this section if there is no one to thank.

== See Also

*ols_begin*


